name: Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: garethr/snykout/action@master
      continue-on-error: true
      with:
        input: fixtures/example.json
    - uses: garethr/snykout/action@master
      continue-on-error: true
      with:
        input: fixtures/example.json
        args: --json
        output: snykout.json
    - uses: actions/upload-artifact@v2
      with:
        path: snykout.json
    - uses: instrumenta/conftest-action@master
      with:
        files: snykout.yaml
